language: cpp
compiler:
  - gcc
sudo: required 
dist: bionic
os: linux
git:
  submodules: false

before_install:
- sudo apt update
- sudo apt install -y ninja-build
- sudo apt install cmake
- git submodule update --init --remote --recursive
- curl -L https://github.com/protocolbuffers/protobuf/releases/download/v3.11.2/protobuf-all-3.11.2.tar.gz -o /tmp/protoc.tar.gz
- mkdir ~/protoc
- tar xvzf /tmp/protoc.tar.gz -C ~/protoc
- cd ~/protoc/protobuf-3.11.2
- ./configure && make && sudo make install
- sudo ldconfig
- export LD_LIBRARY_PATH=/usr/local/lib

script:
- cd /home/travis/build/autostrider/Execution-Manager
- mkdir build
- cd build
- sudo cmake -GNinja .. && sudo ninja
