language: cpp
compiler:
  - gcc
sudo: required
dist: bionic
os: linux
git:
  submodules: false

before_install:
- env
- export SRC_DIR="`pwd`"
# - sudo apt-get update
- sudo apt-get install -y ninja-build
- git submodule update --init --remote --recursive

script:
  - mkdir build
  - cd build
  - sudo cmake -Dstdlib=libstdc++ -GNinja "$SRC_DIR"
  - ninja
