language: cpp
compiler:
  - gcc
sudo: required
dist: bionic
os: linux
git:
  submodules: false

before_install:
# - sudo apt-get update
- sudo apt-get install -y ninja-build
- git submodule update --init --remote --recursive

script:
  - mkdir build
  - pwd
  - cd build
  - sudo env "PATH=$PATH" cmake -GNinja .. . --target install
  - ninja
