language: cpp
compiler:
  - gcc
sudo: required 
dist: bionic
os: linux
git:
  submodules: false

before_install:
# - sudo apt-get update
- sudo apt-get install -y ninja-build
- sudo apt-get install cmake
- git submodule update --init --remote --recursive
- mkdir build
- cd build
- sudo cmake -GNinja ..
- ninja
