language: cpp
compiler:
  - gcc
sudo: required 
dist: bionic
os: linux
git:
  submodules: false

before_install:
# - sudo apt-get update
- sudo apt-get install -y ninja-build
- sudo apt-get install cmake
- git submodule update --init --remote --recursive
- if [ ! -f cppcms-1.0.5.tar.bz2 ]; then wget --no-verbose http://downloads.sourceforge.net/project/cppcms/cppcms/1.0.5/cppcms-1.0.5.tar.bz2; fi
- if [ ! -f cppdb-0.3.1.tar.bz2 ]; then wget --no-verbose http://downloads.sourceforge.net/project/cppcms/cppdb/0.3.1/cppdb-0.3.1.tar.bz2; fi
- if [ ! -f protobuf-cpp-3.0.2.tar.gz ]; then wget --no-verbose https://github.com/google/protobuf/releases/download/v3.0.2/protobuf-cpp-3.0.2.tar.gz; fi


install:
  - export CXX="g++-4.9" CC="gcc-4.9"
  - mkdir cppcms-1.0.5/build && cd cppcms-1.0.5/build && cmake .. && make && sudo make install
  - cd ../..
  - mkdir -p cppdb-0.3.1/build && cd cppdb-0.3.1/build
  - cmake .. && make && sudo make install
  - cd ../..
  - cd protobuf-3.0.2
  - ./configure && make && sudo make install
  - cd ..

script:
- mkdir build
- cd build
- sudo cmake -GNinja .. && sudo ninja
