language: cpp
sudo: required 
dist: bionic
services: docker
git:
  submodules: false

before_install:
- sudo apt update
- git submodule update --init --remote --recursive
- sudo docker pull suliana/rpoto-buf-template
- sudo docker ps -a
- sudo docker container run -d -it suliana/rpoto-buf-template

script:
- cd /home/travis/build/autostrider/Execution-Manager
- mkdir build
- cd build
- cmake -GNinja .. && ninja
