language: cpp
compiler:
  - gcc
sudo: required 
dist: bionic
os: linux
services: docker
git:
  submodules: false

before_install:
- sudo docker pull suliana/rpoto-buf-template
- sudo docker ps -a
- sudo docker container run -d -it suliana/rpoto-buf-template
- apt-get update
- apt-get install -y ninja-build
- apt-get install cmake
- git submodule update --init --remote --recursive

script:
- cd /home/travis/build/autostrider/Execution-Manager
- mkdir build
- cd build
- cmake -GNinja .. && ninja
