language: cpp
compiler:
  - gcc
sudo: required 
dist: bionic
os: linux
git:
  submodules: false

before_install:
# - sudo apt-get update
- sudo apt-get install -y ninja-build
- sudo apt-get install cmake
- git submodule update --init --remote --recursive


install:
 - curl -L https://github.com/google/protobuf/releases/download/v3.6.1/protoc-3.6.1-linux-x86_64.zip -o /tmp/protoc.zip
 - unzip /tmp/protoc.zip -d "$HOME"/protoc

env:
 - PATH=$HOME/protoc/bin:$PATH

script:
- mkdir build
- cd build
- sudo cmake -GNinja .. && sudo ninja
