language: cpp
compiler:
  - gcc
sudo: required 
dist: xenial
os: linux
git:
  submodules: false

before_install:
# - sudo apt-get update
- sudo apt-get install -y ninja-build
- git submodule update --init --remote --recursive
- mkdir build
- cd build

- echo "====================="
- ls -l /etc/systemd/system/
- echo "====================="
- sudo cmake -GNinja ..
- ninja
